// Typed contract clients for Yap's on-chain surface.
// Addresses populate from env after deploy; ABIs are generated from
// contracts/out/ via Foundry and mirrored into lib/abi/.

import type { Abi } from "viem";
import { NETWORK } from "./chains";
import fighterAbi from "./abi/YapFighter.json";
import escrowAbi from "./abi/BattleEscrow.json";
import registryAbi from "./abi/BattleRegistry.json";
import marketplaceAbi from "./abi/YapMarketplace.json";
import rentalEscrowAbi from "./abi/RentalEscrow.json";
import yapInboxAbi from "./abi/YapInbox.json";
import yapSubnameAbi from "./abi/YapSubnameRegistrar.json";
import momentInftAbi from "./abi/MomentINFT.json";

function pick(mainnet: string | undefined, testnet: string | undefined) {
  return (NETWORK === "mainnet" ? mainnet : testnet) ?? "";
}

export const FIGHTER_INFT_ADDRESS = pick(
  process.env.NEXT_PUBLIC_YAP_FIGHTER_ADDR_MAINNET,
  process.env.NEXT_PUBLIC_YAP_FIGHTER_ADDR_TESTNET,
);

export const BATTLE_ESCROW_ADDRESS = pick(
  process.env.NEXT_PUBLIC_BATTLE_ESCROW_ADDR_MAINNET,
  process.env.NEXT_PUBLIC_BATTLE_ESCROW_ADDR_TESTNET,
);

export const BATTLE_REGISTRY_ADDRESS = pick(
  process.env.NEXT_PUBLIC_BATTLE_REGISTRY_ADDR_MAINNET,
  process.env.NEXT_PUBLIC_BATTLE_REGISTRY_ADDR_TESTNET,
);

export const MARKETPLACE_ADDRESS = pick(
  process.env.NEXT_PUBLIC_MARKETPLACE_ADDR_MAINNET,
  process.env.NEXT_PUBLIC_MARKETPLACE_ADDR_TESTNET,
);

export const RENTAL_ESCROW_ADDRESS = pick(
  process.env.NEXT_PUBLIC_RENTAL_ESCROW_ADDR_MAINNET,
  process.env.NEXT_PUBLIC_RENTAL_ESCROW_ADDR_TESTNET,
);

/// CREATE2-deployed YapInbox — same address on testnet + mainnet.
export const YAP_INBOX_ADDRESS = pick(
  process.env.NEXT_PUBLIC_YAP_INBOX_ADDR_MAINNET,
  process.env.NEXT_PUBLIC_YAP_INBOX_ADDR_TESTNET,
);

/// Phase-2 contracts (CREATE2-deployed): label↔tokenId binding,
/// per-round Moment INFTs, and a YapMarketplace instance pointed
/// at Moments for trading.
export const YAP_SUBNAME_ADDRESS = pick(
  process.env.NEXT_PUBLIC_YAP_SUBNAME_ADDR_MAINNET,
  process.env.NEXT_PUBLIC_YAP_SUBNAME_ADDR_TESTNET,
);

export const MOMENT_INFT_ADDRESS = pick(
  process.env.NEXT_PUBLIC_MOMENT_INFT_ADDR_MAINNET,
  process.env.NEXT_PUBLIC_MOMENT_INFT_ADDR_TESTNET,
);

export const MOMENT_MARKET_ADDRESS = pick(
  process.env.NEXT_PUBLIC_MOMENT_MARKET_ADDR_MAINNET,
  process.env.NEXT_PUBLIC_MOMENT_MARKET_ADDR_TESTNET,
);

// ABIs generated by Foundry from contracts/src/*.sol.
// Regenerate with: pnpm contracts:sync-abi (after contracts:build)
// Note: JSON-imported ABIs lose literal type inference; viem still works but
// without strict function-name autocomplete. For full type inference, switch
// to generated TS modules via wagmi-cli or similar.
export const FIGHTER_INFT_ABI = fighterAbi as Abi;
export const BATTLE_ESCROW_ABI = escrowAbi as Abi;
export const BATTLE_REGISTRY_ABI = registryAbi as Abi;
export const MARKETPLACE_ABI = marketplaceAbi as Abi;
export const RENTAL_ESCROW_ABI = rentalEscrowAbi as Abi;
export const YAP_INBOX_ABI = yapInboxAbi as Abi;
export const YAP_SUBNAME_ABI = yapSubnameAbi as Abi;
export const MOMENT_INFT_ABI = momentInftAbi as Abi;
